[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sophus-pybind-stubs"
version = "1.22.10"
description = "Stubs for sophus-pybind"

[tool.setuptools.packages.find]
where = ["./"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]
